from __future__ import annotations
r'''
    Useful methods for partial differential operators.

    This module contains useful functionality to compute and analyze the spectral varieties obtained from
    commuting partial differential operators.

    ::IGNORE AUDIT::

    **Elements provided by the module**
    -----------------------------------------
'''
# ****************************************************************************
#  Copyright (C) 2026 Antonio Jimenez-Pastor <antonio.jimenezp@upm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#                  https://www.gnu.org/licenses/
# ****************************************************************************

import logging

logger = logging.getLogger(__name__)

from functools import lru_cache, reduce
from typing import Callable

from sage.matrix.constructor import matrix
from sage.misc.cachefunc import cached_method
from sage.modules.free_module_element import vector
from sage.rings.integer_ring import ZZ
from sage.structure.element import Element, Matrix, Vector
from sage.structure.parent import Parent

from dalgebra.dpolynomial.dpolynomial import DMonomialGen, DPolynomial

#####################################################################################
###
### GENERIC METHODS FOR DIFFERENTIAL OPERATORS
###
#####################################################################################
def h(L: DPolynomial) -> DPolynomial:
    r'''
        Given a differential operator L, it returns its highest order part h(L).
    '''
    gen = L.parent().gens()[0]
    o = L.order(gen)

    result = 0
    for (c,m) in zip(L.coefficients(), L.monomials()):
        m = L.parent()(m)
        if m.order(gen) == o:
            result += c*m
    return result

def prod_array(vector: Vector, operators: tuple[DPolynomial]) -> DPolynomial:
    r'''
        Given a vector of exponents and a list of differential operators, it returns the product of
        the corresponding powers of the operators.
    '''
    if len(vector) != len(operators):
        raise ValueError(f"Incoherent sizes")
    if len(vector) == 0:
        return 1
        
    gen = operators[0].parent().gens()[0]
    powers = [op.sym_power(e,gen) for e,op in zip(vector, operators)]
    return reduce(lambda p,q : p.dot(q, gen), powers)

######################################################################################
###
### METHODS SPECIFIC FOR A SET OF OPERATORS
###
######################################################################################
class CommutingPDOHighest:
    r'''
        Class for handling commuting partial differential operators and their highest order parts.
    '''
    def __init__(self, operators: tuple[DPolynomial], gen: DMonomialGen, field: Parent):
        self.__operators = operators
        self.__gen = gen
        self.__field = field
        self.__orders = [op.order(gen) for op in operators]
        self.__can_basis = [vector(ZZ,[1 if i == j else 0 for j in range(len(operators))]) for i in range(len(operators))]

    @cached_method
    def T(self, n: int) -> tuple[Vector]:
        r'''
            Return the exponents of monomials in the operators, for a total order `n`.
        '''
        if n < 0: return list()
        elif n == 0: return [vector(ZZ,len(self.__operators))]
        else:
            A = [[el + self.__can_basis[i] for el in self.T(n-self.__orders[i])] for i in range(len(self.__operators))]
            ## We make the union
            S = A[0]
            for i in range(1,len(A)):
                S += [el for el in A[i] if el not in S]
            return S
        
    @cached_method
    def P(self, n: int) -> tuple[DPolynomial]:
        r'''
            Given a tuple of commuting differential operators (i.e., a list of DPolynomial), it returns the set of
            products of the operators of total order n.
        '''
        return [prod_array(el, self.__operators) for el in self.T(n)]
    
    @cached_method
    def H(self, n: int) -> tuple[DPolynomial]:
        r'''
            Returns the set of highest order parts of the products of the operators of total order `n`.
        '''
        return [h(el) for el in self.P(n)]
    
    def to_vector(self, element: DPolynomial) -> Vector:
        r'''
            Given a differential operator element, it returns the vector representation of the element in the 
            basis generated by the corresponding monomials.
        '''
        order = element.order(self.__gen)
        result = [0 for _ in range(self.dim(order))]
        parent = element.parent()
        base = parent.base()
        
        basis = self.monomials(order)
        
        for c,m in zip(element.coefficients(), element.monomials()):
            for t, cc in c.conditions_to_zero():
                mon = base(t)*parent(m)
                if mon not in basis:
                    raise ValueError(f"Found an incompatible term in {element} for the C-basis {basis}")
                result[basis.index(mon)] += cc
        return vector(self.__field, result)
    
    def from_vector(self, vector: Vector, order: int, t: str = "P") -> DPolynomial:
        r'''
            Given a vector, an order and a type t ("P" or "H"),
            it returns the corresponding differential operator that is the linear combination of the products
            (if t = "P") or of the highest order parts (if t = "H") of total order equal to order, with coefficients
            given by the vector.
        '''
        if len(vector) != len(self.T(order)):
            raise ValueError("Incongruent dimension for vector")

        if t == "P":
            elements = self.P(order)
        elif t == "H":
            elements = self.H(order)
        else:
            raise ValueError("Unexpected type of element to expand")

        return sum(v*e for (v,e) in zip(vector, elements))

    @cached_method    
    def monomials(self, n: int) -> tuple[DPolynomial]:
        r'''
            Returns the set of highest order parts of the products of the operators of total order n.
        '''
        Hs = self.H(n)
        if len(Hs) == 0:
            return None, tuple()
        
        parent = self.__operators[0].parent()
        base = parent.base() # without diff. variable
        parts = [list(zip(h.coefficients(),h.monomials())) for h in Hs]
        basis = []
        for part in parts:
            for c,m in part:
                for t,_ in c.conditions_to_zero():
                    mon = base(t)*parent(m)
                    if mon not in basis:
                        basis += [mon]
        return tuple(basis)
    
    @cached_method
    def system(self, n: int) -> Element:
        r'''
            Returns the matrix of the system defined by the highest order parts of the products of total order n.
        '''
        ## We compute the list of monomials that will be a basis as a C-vector space
        Hs = self.H(n)
        basis = self.monomials(n)

        matr = [self.to_vector(hs) for hs in Hs]
        M = matrix(self.__field, matr).transpose()
        return M

    def dim(self, n: int) -> int:
        r'''
            Returns the dimension of the space of highest order parts of the products of total order n.

            This is equivalent to the number of monomials of total order n.
        '''
        return len(self.monomials(n))
    
    def cancelling_solutions(self, vector: Vector, order: int) -> tuple[Element,Element] | str:
        r'''
            Given a vector and an order, it returns all solutions the system defined by the highest order parts 
            of the products of total order n equal to the vector in the format of concrete solution and 
            solution to homogeneous system.
        '''
        S = self.system(order)
        
        try:
            solution = S.solve_right(vector)
        except ValueError:
            print("No solution")
            return
        kernel = S.right_kernel_matrix()
        return solution, kernel
