##############################################################################################
### Action for the Continuous-Integration of the package `dalgebra`
## This module contains two actions:
##    - Linting --> guarantees the proper format according to Pylint
##    - Testing --> run the tests in the documentation to guarantee the correctness in new version of the code.
####
##############################################################################################
name: CI-Actions

on: # only used on pushes or pull_request over the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

##############################################################################################
##############################################################################################

jobs:
  linting: # Job for lint the repository
    runs-on: ubuntu-latest
    container: 
        image: sagemath/sagemath:latest # sagemath/sagemath:9.3.beta8 # old version to allow proper working on github machines
        options: --user root
    steps:
    - uses: actions/checkout@v3
    - name: Installing git and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends git apt-transport-https ca-certificates
        sudo apt-get clean
    - name: Install package
      run: |
        sage -pip install --upgrade .
    - name: Install pylint
      run: |
        sage -pip install pylint
    - name: Linting code for repository
      run: |
        /home/sage/sage/venv/bin/pylint ./dalgebra  --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,\
        global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,\
        bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,\
        E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,\
        E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,\
        E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,\
        E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,\
        E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,\
        E1303,E1304,E1305,E1306,E1310,E1700,E1701,unused-import,unused-argument \
        --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text
  
  ##############################################################################################

  testing: # Job for running the automatic tests in Sagemath
    runs-on: ubuntu-latest
    container: 
        image: sagemath/sagemath:latest # sagemath/sagemath:9.3.beta8 # old version to allow proper working on github machines
        options: --user root
    steps:
    - uses: actions/checkout@v3
    - name: Installing git and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends git apt-transport-https ca-certificates
        sudo apt-get clean
    - name: Install package
      run: |
        sage -pip install --upgrade .
    - name: Running sage tests
      run: |
        sage -t dalgebra

##############################################################################################
##############################################################################################
